# Generated by Django 4.1.6 on 2023-02-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modelo', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=14)),
                ('resumo', models.TextField()),
                ('dataNascimento', models.DateField()),
                ('dataCadastro', models.DateField(auto_now=True)),
                ('tipoCliente', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qtd_estoque', models.IntegerField()),
                ('descricao', models.TextField()),
                ('validade', models.DateField()),
                ('disponibilidade', models.BooleanField()),
                ('categoria_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.categorias')),
            ],
        ),
    ]
