# Generated by Django 4.1.5 on 2023-02-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='categoria',
        ),
    ]
