# Generated by Django 4.1.5 on 2023-02-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_remove_produtos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nome_modelo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
