# Generated by Django 4.1.6 on 2023-02-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_tipo_alter_clientes_tipocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tipoCliente',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Premium'), ('M', 'Master')], default='F', max_length=1),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
