# Generated by Django 4.1.6 on 2023-02-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_clientes_tipocliente_delete_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name_plural': 'Produtos'},
        ),
    ]
