# Generated by Django 4.1.6 on 2023-02-16 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_categorias_options_alter_clientes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1, message='O preço deve ser igual ou maior que 1 real')]),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='qtd_estoque',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='A quantidade no estoque deve ser maior ou igual a 0'), django.core.validators.MaxValueValidator(1000, message='Valor máximo excedido!')]),
        ),
    ]
