# Generated by Django 4.1.7 on 2023-04-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produtos_num_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='num_parcelas',
            field=models.IntegerField(default=True),
        ),
    ]
