# Generated by Django 4.1.7 on 2023-04-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_produtos_num_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='revendedora',
            field=models.CharField(default='Magazine', max_length=50),
        ),
    ]
