# Generated by Django 4.1.7 on 2023-04-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_produtos_revendedora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='revendedora',
            new_name='vendedora',
        ),
    ]
