# Generated by Django 4.1.7 on 2023-04-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_rename_revendedora_produtos_vendedora'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='avaliacao',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.PROTECT, to='loja.produtos'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='foto',
            field=models.ImageField(default='foto.png', upload_to='cliente'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_comentario', models.CharField(max_length=20)),
                ('comentario', models.TextField()),
                ('avaliacao_produto', models.ForeignKey(default='5', on_delete=django.db.models.deletion.PROTECT, to='loja.produtos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.clientes')),
            ],
        ),
    ]
