# Generated by Django 4.1.7 on 2023-04-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_clientes_avaliacao_clientes_foto_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('codigo_hex', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='cores',
            field=models.ManyToManyField(to='loja.cor'),
        ),
    ]
