# Generated by Django 4.1.6 on 2023-02-24 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modelo', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qtd_estoque', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='A quantidade no estoque deve ser maior que 0')])),
                ('descricao', models.TextField()),
                ('disponibilidade', models.BooleanField()),
                ('categoria_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.categorias')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='PedidoCompleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado_pagamento', models.CharField(choices=[('A', 'Aprovado'), ('R', 'Recusado'), ('P', 'Processamento/Pendente')], default='P', max_length=1)),
                ('tipo_pagamento', models.CharField(choices=[('B', 'Boleto'), ('C', 'Cartão crédito'), ('D', 'Cartão débito'), ('P', 'Pix')], default='P', max_length=1)),
                ('estado_pedido', models.CharField(choices=[('A', 'Aprovado'), ('R', 'Recusado'), ('P', 'Processamento/Pendente')], default='A', max_length=1)),
                ('data_venda', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.clientes')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='A quantidade deve ser maior que 1')])),
                ('total_pagamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedidocompleto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.produtos')),
            ],
            options={
                'verbose_name_plural': 'Item Pedido',
            },
        ),
    ]
